### ISSUE TITLE
AssertionError on double voting and invalid candidates tests

### ISSUE THREAD

**Issue by matthewclosson** [dappuniversity/election#1]
> 2 failing
> 
>   1) Contract: Election throws an exception for invalid candiates:
>      AssertionError: error message must contain revert
>       at test/Election.js:63:13
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:188:7)
> 
>   2) Contract: Election throws an exception for double voting:
>      AssertionError: error message must contain revert
>       at test/Election.js:87:13
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:188:7)

Possibly a problem with the require function?

**Comment by gwmccubbin** [comment]
@matthewclosson Thanks for the submission! Which release version did you clone when you got this error? Do you always get this error when you run this test? Or is it intermittent?

**Comment by pauluhn** [comment]
for whatever reason, it doesn't throw exception. i fixed the test to check for failed tx status instead: https://github.com/pauluhn/election/blob/paul/test/election.js#L54

**Comment by gwmccubbin** [comment]
@pauluhn Thanks for the tip!

**Comment by shubham5048jaiswal** [comment]
C:\Users\DINESH JAISWAL\Election2022>truffle console
truffle(development)> Election.deployed().then(function(instance) {app = instance})
Uncaught:
Error: Election has not been deployed to detected network (network/artifact mismatch)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Function.deployed (C:\Users\DINESH JAISWAL\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\contract\constructorMethods.js:83:1)
    at Object.checkNetworkArtifactMatch (C:\Users\DINESH JAISWAL\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\utils\index.js:245:1)
truffle(development)>

**Comment by hiraahmad6** [comment]
1) Contract: Election
       throws an exception for double voting:
     AssertionError: error message must contain revert

What will be the solution?

**Comment by hiraahmad6** [comment]
1) Contract: Election
       throws an exception for double voting:
     AssertionError: candidate 2 did not receive any votes: expected <BN: 0> to equal 1

What will be the solution?

**Comment by hiraahmad6** [comment]
it("throws an exception for double voting", function() {
return Election.deployed().then(function(instance) {
electionInstance = instance;
candidateId = 2;
electionInstance.vote(candidateId, { from: accounts[1] });
return electionInstance.candidates(candidateId);
}).then(function(candidate) {
var voteCount = candidate[2];
assert.equal(voteCount, 1, "accepts first vote");
// Try to vote again
return electionInstance.vote(candidateId, { from: accounts[1] });
}).then(assert.fail).catch(function(error) {
assert(error.message, "error message must contain revert");
return electionInstance.candidates(1);
}).then(function(candidate1) {
var voteCount = candidate1[2];
assert.equal(voteCount, 1, "candidate 1 did not receive any votes");
return electionInstance.candidates(2);
}).then(function(candidate2) {
var voteCount = candidate2[2];
assert.equal(voteCount, 0, "candidate 2 did not receive any votes");
});
});
});

My last test executes successfully by changing the code as written above.

**Comment by sampriti026** [comment]
Alright, I think I figured it out. Using the above code would only check for failed transactions, which could arise from many reasons. Thus, though the test would pass, it wouldn't necessarily imply that the transaction failed because the voter was trying to double vote. 
After executing only the first part of the code where we try to register our first vote, the test still produced the following error: 
_expected <BN: 0> to equal 1_  . Which probably means that the count of vote was never being increased. I changed the first five lines of code from:

```
it("throws an exception for double voting", function() {
    return Election.deployed().then(function(instance) {
      electionInstance = instance;
      candidateId = 2;
      electionInstance.vote(candidateId, { from: accounts[1] });

```
to this: (added async-await before the function and the action)
```
  it("throws an exception for double voting", function() {
    return Election.deployed().then(async function(instance) {
      electionInstance = instance;
      candidateId = 2;
      await electionInstance.vote(candidateId, { from: accounts[1] });
```
Now, all the tests are passing while ensuring that the first vote is being registered( checking for the increased vote count in the last assert statement returns true).

Let me know if this works or if it is a faulty analysis.

**Comment by HimikaP** [comment]
> it("throws an exception for double voting", function() { return Election.deployed().then(function(instance) { electionInstance = instance; candidateId = 2; electionInstance.vote(candidateId, { from: accounts[1] }); return electionInstance.candidates(candidateId); }).then(function(candidate) { var voteCount = candidate[2]; assert.equal(voteCount, 1, "accepts first vote"); // Try to vote again return electionInstance.vote(candidateId, { from: accounts[1] }); }).then(assert.fail).catch(function(error) { assert(error.message, "error message must contain revert"); return electionInstance.candidates(1); }).then(function(candidate1) { var voteCount = candidate1[2]; assert.equal(voteCount, 1, "candidate 1 did not receive any votes"); return electionInstance.candidates(2); }).then(function(candidate2) { var voteCount = candidate2[2]; assert.equal(voteCount, 0, "candidate 2 did not receive any votes"); }); }); });
> 
> My last test executes successfully by changing the code as written above.

this works [🎉](https://emojipedia.org/party-popper/)[🎉](https://emojipedia.org/party-popper/)[🎉](https://emojipedia.org/party-popper/)

**Comment by BrianGikaria** [comment]
> Alright, I think I figured it out. Using the above code would only check for failed transactions, which could arise from many reasons. Thus, though the test would pass, it wouldn't necessarily imply that the transaction failed because the voter was trying to double vote. After executing only the first part of the code where we try to register our first vote, the test still produced the following error: _expected <BN: 0> to equal 1_ . Which probably means that the count of vote was never being increased. I changed the first five lines of code from:
> 
> ```
> it("throws an exception for double voting", function() {
>     return Election.deployed().then(function(instance) {
>       electionInstance = instance;
>       candidateId = 2;
>       electionInstance.vote(candidateId, { from: accounts[1] });
> ```
> 
> to this: (added async-await before the function and the action)
> 
> ```
>   it("throws an exception for double voting", function() {
>     return Election.deployed().then(async function(instance) {
>       electionInstance = instance;
>       candidateId = 2;
>       await electionInstance.vote(candidateId, { from: accounts[1] });
> ```
> 
> Now, all the tests are passing while ensuring that the first vote is being registered( checking for the increased vote count in the last assert statement returns true).
> 
> Let me know if this works or if it is a faulty analysis.

Thank you, sir; it works.

**Comment by MahadMuhammad** [comment]
_Originally posted by @sampriti026 in https://github.com/dappuniversity/election/issues/1#issuecomment-1170044274_


> to this: (added async-await before the function and the action)
> 
> ```
>   it("throws an exception for double voting", function() {
>     return Election.deployed().then(async function(instance) {
>       electionInstance = instance;
>       candidateId = 2;
>       await electionInstance.vote(candidateId, { from: accounts[1] });
> ```
> Let me know if this works or if it is a faulty analysis.

It works. Thanks for the explanation :)
