### ISSUE TITLE
web3.eth.accounts[0] returns undefined and app.vote(1,{ from:web3.eth.accounts[0] }) is giving error

### ISSUE THREAD

**Issue by nik92eth** [dappuniversity/election#53]
If anybody is struggling with this. [Solution](https://stackoverflow.com/questions/61790374/web3-eth-accounts0-returns-undefined-and-app-vote1-fromweb3-eth-accounts0)

**Comment by eirchaid** [comment]
Did you solve the problems?
I have this one:
truffle(development)> app.vote(1, {from:accounts[2]})
evalmachine.<anonymous>:0
app.vote(1, {from:accounts[0]})
^

Uncaught ReferenceError: app is not defined
    at evalmachine.<anonymous>:0:1
    at sigintHandlersWrap (vm.js:272:15)
    at Script.runInContext (vm.js:127:14)
    at runScript (C:\Users\Eirini\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:227:1)
    at Console.interpret (C:\Users\Eirini\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:242:1)
    at ReplManager.interpret (C:\Users\Eirini\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\repl.js:129:1)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:760:10)
    at REPLServer.emit (events.js:315:20)

**Comment by eirchaid** [comment]
i fixed it!
